spring:
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':  # Applies to all paths
                    allowedOrigins: "*"
                    allowedMethods: GET, POST, PUT, DELETE, OPTIONS
                    allowedHeaders: "*"
            routes:
                - id: auth_route
                  uri: lb://authService
                  predicates:
                    - Path=/api/auth/**
                - id: booking_route
                  uri: lb://bookingService
                  predicates:
                    - Path=/api/bookings/**